export interface PlanoEngineAPI {
  dims: Array<{ id: string; x1: number; y1: number; x2: number; y2: number; L: number }>;
  textAnnots: Array<{
    x: number; y: number;
    lblOffX?: number; lblOffY?: number;
    id: string;
    fontMm?: number;
    textAngle?: number;
    boxW: number;
    text: string;
    _box?: { x: number; y: number; w: number; h: number };
  }>;
  areas: Array<{
    net?: string;
    id: string;
    pts: number[][];
    color?: string;
    labelX: number;
    labelY: number;
    labelAngle?: number;
    label?: string;
    areaM2?: number;
    _polyBox?: { x: number; y: number; w: number; h: number };
    _labelBox?: {
      cx: number; cy: number; w: number; h: number; angle: number;
      minX: number; minY: number; maxX: number; maxY: number;
      corners: Array<{ x: number; y: number }>;
    } | null;
  }>;
  ramales: Array<{
    net: string;
    id: string;
    pts: number[][];
    tipo?: string;
    padre?: string | null;
    ini?: string;
    fin?: string;
    label?: string;
    totalL?: number;
    material?: string;
    diametro?: string;
    pendiente?: number;
    piso?: string;
    dz?: string;
    uc?: number;
    labelX: number;
    labelY: number;
    labelAngle?: number;
    _labelBox?: {
      cx: number; cy: number; w: number; h: number; angle: number;
      minX: number; minY: number; maxX: number; maxY: number;
      corners: Array<{ x: number; y: number }>;
    } | null;
  }>;
  bajantes: Array<{
    net: string;
    id: string;
    x: number;
    y: number;
    labelAngle?: number;
    labelX: number;
    labelY: number;
    recibeDeIds?: string[];
    descargaEnId?: string | null;
    code?: string;
    hVert?: number;
    dNominal?: string;
    tipo?: string;
    nptBase?: number;
    nptCima?: number;
    piso?: string;
    pisoBase?: string;
    pisoCima?: string;
    totalL?: number;
    pendiente?: number;
    alimentaIds?: string[];
    ucAcum?: number;
    ucExtra?: number;
    area_m2?: number;
    lblOffX?: number;
    lblOffY?: number;
    desplazamientos?: Record<string, { dx: number; dy: number; Ldesvio: null }>;
    _circ?: { x: number; y: number; r: number };
    _ghost?: { x: number; y: number; r: number };
    _labelBox?: {
      cx: number; cy: number; w: number; h: number; angle: number;
      minX: number; minY: number; maxX: number; maxY: number;
      corners: Array<{ x: number; y: number }>;
    } | null;
  }>;
  selId: string | null;
  _hiddenNets: Set<string>;
  _lockedNets: Set<string>;
  activeNet: string;
  mouseX: number;
  mouseY: number;
  zoom: number;
  snapMode: boolean;
  tool: string;
  tipoTramo: string;
  scaleM: number;
  canv: HTMLCanvasElement;
  padreTributario: string | null;
  activeRamal: { net: string; pts: number[][]; tipo: string; padre?: string | null; totalL: number } | null;
  activeArea: { pts: number[][]; color?: string } | null;
  nivelActual: { label?: string; npt?: number; n?: string } | null;
  _dimStart: { x: number; y: number } | null;
  _netCounts: Record<string, Record<string, number>>;
  _ramalDefaults: { material: string; diametro: string; pendiente: number } | null;
  _dirty: boolean;
  nptLevels: Array<{ label?: string; npt?: number; n?: string }>;
  panning: boolean;
  panX0: number;
  panY0: number;
  ghostDrag: { id: string; startX: number; startY: number; baseDx: number; baseDy: number } | null;
  lblDrag: { id: string; offX: number; offY: number } | null;
  txtDrag: { id: string; startX: number; startY: number; origX: number; origY: number } | null;
  bajDrag: { id: string; offX: number; offY: number } | null;
  ptDrag: { id: string; ptIdx: number } | null;
  areaDrag: { id: string; startX: number; startY: number } | null;
  MM: {
    lblName: number;
    lblInfo: number;
    lblCode: number;
    flowEmoji: number;
    coord: number;
  };
  toCvs(px: number, py: number): { x: number; y: number };
  toPlane(cx: number, cy: number): { x: number; y: number };
  mm2cvs(mm: number): number;
  pxToM(px: number): number;
  snapAngle(x0: number, y0: number, x1: number, y1: number): { x: number; y: number };
  snapToExisting(x: number, y: number): { x: number; y: number } | null;
  snapPreviewToPadre(x: number, y: number): { x: number; y: number } | null;
  getBajantesFantasma(): Array<{
    net: string;
    id: string;
    x: number;
    y: number;
    tipo?: string;
    desplazamientos?: Record<string, { dx: number; dy: number; Ldesvio: null }>;
    _ghost?: { x: number; y: number; r: number };
  }>;
  render(): void;
  _emitSelect(el: unknown): void;
  _emitStatus(msg: string): void;
  _markDirty(): void;
  _statusMsg(): string;
  _renumberRamales(netId: string): void;
  selectAt(cx: number, cy: number): void;
  getSelected(): { id: string; pts?: number[][] } | null;
  deleteSelected(): void;
}
