export const PlanosTab_S1: React.CSSProperties = {
  padding: '4px 12px',
  background: 'var(--bg3)',
  border: '1px solid var(--line)',
  borderRadius: 'var(--r)',
  color: 'var(--txt2)',
  cursor: 'pointer',
  fontSize: 12,
  fontWeight: 700,
  display: 'flex',
  alignItems: 'center',
  gap: 4,
};
export const PlanosTab_S2: React.CSSProperties = {
  padding: '4px 14px',
  background: 'rgba(14,204,122,0.12)',
  border: '1.5px solid rgba(14,204,122,0.3)',
  borderRadius: 'var(--r)',
  color: '#0ECC7A',
  cursor: 'pointer',
  fontSize: 12,
  fontWeight: 700,
  whiteSpace: 'nowrap',
};
export const PlanosTab_S3: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: 8,
  padding: '6px 12px',
  borderBottom: '1px solid var(--line)',
  flexShrink: 0,
  background: 'var(--bg)',
  minHeight: 36,
};
export const PlanosTab_S4: React.CSSProperties = {
  padding: '3px 10px',
  background: 'rgba(0,220,229,0.08)',
  border: '1px solid rgba(0,220,229,0.3)',
  borderRadius: 'var(--r)',
  color: '#00dce5',
  fontWeight: 600,
  fontSize: 12,
  cursor: 'pointer',
  whiteSpace: 'nowrap',
};
export const PlanosTab_S5: React.CSSProperties = {
  position: 'absolute',
  inset: 0,
  zIndex: 10,
  background: 'rgba(0,220,229,.12)',
  border: '3px dashed rgba(0,220,229,.5)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  pointerEvents: 'none',
};
export const PlanosTab_S6: React.CSSProperties = {
  flex: 1,
  width: '100%',
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  justifyContent: 'center',
  gap: 12,
  background: 'var(--bg)',
  border: 'none',
  padding: 0,
  fontFamily: 'inherit',
  color: 'inherit',
  textAlign: 'center',
  cursor: 'pointer',
  position: 'relative',
};
export const PlanosTab_S7: React.CSSProperties = {
  width: '100%',
  padding: '10px',
  background: 'rgba(0,220,229,0.06)',
  border: '1.5px dashed rgba(0,220,229,0.3)',
  borderRadius: 'var(--r)',
  color: '#00dce5',
  fontWeight: 600,
  fontSize: 12,
  cursor: 'pointer',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  gap: 5,
  transition: 'all .15s',
};
export const PlanosTab_S8: React.CSSProperties = {
  padding: '7px 10px',
  fontSize: 12,
  fontWeight: 700,
  color: 'var(--txt3)',
  borderBottom: '1px solid var(--line)',
  flexShrink: 0,
  display: 'flex',
  alignItems: 'center',
  gap: 5,
  textTransform: 'uppercase',
  letterSpacing: 0.5,
};
export const PlanosTab_S9: React.CSSProperties = {
  flex: 1,
  width: '100%',
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  justifyContent: 'center',
  padding: 20,
  gap: 8,
  background: 'transparent',
  border: 'none',
  fontFamily: 'inherit',
  cursor: 'pointer',
  fontSize: 12,
  color: 'var(--txt4)',
  textAlign: 'center',
  lineHeight: 1.6,
};
export const PlanosTab_S10: React.CSSProperties = {
  flex: 1,
  overflowY: 'auto',
  display: 'flex',
  flexDirection: 'column',
  gap: 6,
  padding: '8px 10px',
  listStyle: 'none',
  margin: 0,
};
export const PlanosTab_S11: React.CSSProperties = {
  padding: '1px 6px',
  background: 'rgba(14,204,122,0.12)',
  border: '1px solid rgba(14,204,122,0.3)',
  borderRadius: 'var(--r)',
  color: '#0ECC7A',
  cursor: 'pointer',
  fontSize: 12,
  fontWeight: 700,
  transition: 'all 0.15s ease',
  whiteSpace: 'nowrap',
};
export const PlanosTab_S12: React.CSSProperties = {
  padding: '3px 6px',
  fontSize: 12,
  fontWeight: 600,
  borderRadius: 'var(--r)',
  border: '1px solid var(--line)',
  background: 'var(--bg3)',
  color: '#ef5350',
  cursor: 'pointer',
  transition: 'all 0.15s ease',
  whiteSpace: 'nowrap',
};
export const PlanosTab_S13: React.CSSProperties = {
  padding: '7px 10px',
  fontSize: 12,
  fontWeight: 700,
  color: 'var(--txt3)',
  borderBottom: '1px solid var(--line)',
  flexShrink: 0,
  display: 'flex',
  alignItems: 'center',
  gap: 5,
  textTransform: 'uppercase',
  letterSpacing: 0.5,
};
export const PlanosTab_S14: React.CSSProperties = {
  padding: '3px 6px',
  fontSize: 12,
  fontWeight: 600,
  borderRadius: 'var(--r)',
  border: '1px solid var(--line)',
  background: 'var(--bg3)',
  color: '#ef5350',
  cursor: 'pointer',
  flexShrink: 0,
  transition: 'all 0.15s ease',
  whiteSpace: 'nowrap',
};
export const PlanosTab_reqBtnBase: React.CSSProperties = {
  width: '100%',
  padding: '6px 8px',
  borderRadius: 'var(--r)',
  cursor: 'pointer',
  fontSize: 12,
  transition: 'all .2s ease',
  marginBottom: 4,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  gap: 4,
};
export const PlanosTab_pendingLi: React.CSSProperties = {
  padding: '10px',
  borderRadius: 'var(--r)',
  display: 'flex',
  flexDirection: 'column',
  gap: 6,
  transition: 'all 0.15s ease',
};
export const PlanosTab_verBtn: React.CSSProperties = {
  padding: '3px 6px',
  fontSize: 12,
  fontWeight: 600,
  borderRadius: 'var(--r)',
  border: '1px solid var(--line)',
  cursor: 'pointer',
  transition: 'all 0.15s ease',
  whiteSpace: 'nowrap',
};
