// Rejillas de ventilación para recintos con gas — NTC 3631 (3ª actualización).
// Port de los archivos fuente del módulo (DOCX especificación v3.0, XLSX NTC3631 y HTML v15):
// constantes normativas, soluciones de ventilación, presets de gasodomésticos y catálogo
// base de rejillas comerciales con área efectiva declarada por el fabricante.

/** Constantes NTC 3631 (cm/cm²/mm). Numerales en comentario. */
export const NTC3631 = {
  VOL_KW: 3.4, // m³ por kW: límite recinto suficiente/confinado (4.1.1)
  EXT_DIR: 6, // cm²/kW por abertura, directa o conducto vertical (4.2.1 a)
  EXT_HOR: 11, // cm²/kW por abertura, conducto horizontal (4.2.1 b)
  UNICA: 11, // cm²/kW, Método 2 una abertura, mayor de esto y Σ conectores (4.2.2)
  INT_MISMO: 22, // cm²/kW, interior mismo piso (4.1.2 a)
  INT_MISMO_MIN: 645, // cm², mínimo absoluto interior mismo piso (4.1.2 a)
  INT_OTRO: 44, // cm²/kW, interior otro piso (4.1.2 b)
  H_SUP: 180, // cm, borde inferior mínimo de la abertura superior (4.1.2, 4.2)
  H_INF: 30, // cm, borde superior máximo de la abertura inferior (4.1.2, 4.2.1)
  ZOCALO: 4, // cm, separación práctica de la rejilla inferior al piso
  MALLA: 6.3, // mm, luz mínima de malla de protección (5)
  MIN_LADO: 8, // cm, dimensión menor mínima de toda abertura (4.1.2, 4.2, 4.3)
  ALT_TOPE: 30, // cm, alternativa: abertura superior comenzando a ≤30 cm del techo
  ALT_HMAX: 60, // cm, altura máxima de la banda de ubicación alternativa
} as const;

/** Soluciones de ventilación (columna Tipo de Ventilación). Clave → config del cálculo. */
export const SOL: Record<
  string,
  {
    t: string;
    com: 'directa' | 'horizontal';
    met: '1' | '2';
    adj: boolean;
    piso?: 'mismo' | 'otro';
    comb?: boolean;
  }
> = {
  'ext-dir': { t: 'Exterior · directa/vertical', com: 'directa', met: '1', adj: false },
  'ext-hor': { t: 'Exterior · conducto horizontal', com: 'horizontal', met: '1', adj: false },
  'ext-m2': { t: 'Exterior · método 2 (una)', com: 'directa', met: '2', adj: false },
  'int-mismo': { t: 'Interior · mismo piso', com: 'directa', met: '1', adj: true, piso: 'mismo' },
  'int-otro': { t: 'Interior · otro piso', com: 'directa', met: '1', adj: true, piso: 'otro' },
  'comb-dir': {
    t: 'Combinación int.+ext. · directa',
    com: 'directa',
    met: '1',
    adj: false,
    comb: true,
  },
  'comb-hor': {
    t: 'Combinación int.+ext. · conducto horiz.',
    com: 'horizontal',
    met: '1',
    adj: false,
    comb: true,
  },
};

/** Grupos de gasodomésticos de la tabla (columnas Estufa/Calent./Otros). */
/** Grupos de gasodomésticos de la tabla (columnas Estufa/Calent./Otros). */
export type GrupoGasod = 'estufa' | 'calent' | 'otros';
/** Tipo de artefacto NTC 3631 por defecto de cada grupo (A suma, B suma con ducto, C estanco). */
export const TIPO_DEFAULT: Record<GrupoGasod, 'A' | 'B' | 'C'> = {
  estufa: 'A',
  calent: 'B',
  otros: 'A',
};
/** Referencia comercial de rejilla. aef = área efectiva libre (cm², ficha del fabricante);
 *  w×h = abertura útil en cm. aef 0/undefined = sin dato → no se sugiere (num. 5). */
export interface RejRef {
  marca: string;
  ref: string;
  tipo: string;
  ext: string;
  w: number;
  h: number;
  aef: number;
  uso: 'ambos' | 'ext' | 'int';
  origen: 'nacional' | 'importado';
}

/** Medidas comerciales de respaldo cuando ninguna referencia del catálogo cubre el área. */
export const COMERCIALES: Array<[number, number]> = [
  [10, 10],
  [15, 10],
  [20, 10],
  [25, 10],
  [30, 10],
  [20, 15],
  [25, 15],
  [30, 15],
  [40, 15],
  [20, 20],
  [30, 20],
  [40, 20],
  [50, 20],
  [60, 20],
  [40, 25],
  [50, 25],
  [60, 25],
  [40, 30],
  [60, 30],
  [80, 30],
];

/** Catálogo base (79 refs): Silplas 10, Grival 3 (sin aef), Laminaire L-OL-4 24,
 *  Laminaire L-DGD 17, Koolair 13, TROX 12. Fuentes: fichas del fabricante /
 *  catálogo HVAC 2025 (Laminaire, ft²×929 redondeado abajo) / catálogos españoles. */
export const CATALOGO_BASE: RejRef[] = [
  {
    marca: 'Silplas',
    ref: '510-030-15',
    tipo: 'Corriente',
    ext: '22,5×22,5',
    w: 20,
    h: 20,
    aef: 177,
    uso: 'ambos',
    origen: 'nacional',
  },
  {
    marca: 'Silplas',
    ref: '510-074-15',
    tipo: 'Colmena',
    ext: '22,5×22,5',
    w: 20,
    h: 20,
    aef: 237,
    uso: 'ambos',
    origen: 'nacional',
  },
  {
    marca: 'Silplas',
    ref: '510-046-15',
    tipo: 'Corriente',
    ext: '24×24',
    w: 21.6,
    h: 21.6,
    aef: 244,
    uso: 'ambos',
    origen: 'nacional',
  },
  {
    marca: 'Silplas',
    ref: '510-040-15',
    tipo: 'Persiana',
    ext: '25×25',
    w: 21,
    h: 21,
    aef: 249,
    uso: 'ambos',
    origen: 'nacional',
  },
  {
    marca: 'Silplas',
    ref: '510-081-15',
    tipo: 'Persiana',
    ext: '21×35',
    w: 16,
    h: 30,
    aef: 257,
    uso: 'ambos',
    origen: 'nacional',
  },
  {
    marca: 'Silplas',
    ref: '510-069-15',
    tipo: 'Colmena',
    ext: '38×16',
    w: 34,
    h: 13,
    aef: 286,
    uso: 'ambos',
    origen: 'nacional',
  },
  {
    marca: 'Silplas',
    ref: '510-043-15',
    tipo: 'Persiana',
    ext: '30×30',
    w: 25.4,
    h: 25.4,
    aef: 364,
    uso: 'ambos',
    origen: 'nacional',
  },
  {
    marca: 'Silplas',
    ref: '510-048-15',
    tipo: 'Corriente',
    ext: '28×28',
    w: 25.5,
    h: 25.5,
    aef: 365,
    uso: 'ambos',
    origen: 'nacional',
  },
  {
    marca: 'Silplas',
    ref: '0303615 (Coval)',
    tipo: 'Colmena',
    ext: '45×25',
    w: 41,
    h: 21,
    aef: 645,
    uso: 'ambos',
    origen: 'nacional',
  },
  {
    marca: 'Silplas',
    ref: '510-055-15',
    tipo: 'Lineal desmontable',
    ext: '100×10',
    w: 100,
    h: 10,
    aef: 679,
    uso: 'ambos',
    origen: 'nacional',
  },
  {
    marca: 'Grival',
    ref: '937010001',
    tipo: 'Sencilla',
    ext: '20×20',
    w: 20,
    h: 20,
    aef: 0,
    uso: 'ambos',
    origen: 'nacional',
  },
  {
    marca: 'Grival',
    ref: '937000001',
    tipo: 'Persiana',
    ext: '20×20',
    w: 20,
    h: 20,
    aef: 0,
    uso: 'ambos',
    origen: 'nacional',
  },
  {
    marca: 'Grival',
    ref: '937310001',
    tipo: 'Corriente',
    ext: '30×30',
    w: 30,
    h: 30,
    aef: 0,
    uso: 'ambos',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 12x12',
    tipo: 'Louver exterior',
    ext: '12×12"',
    w: 30.5,
    h: 30.5,
    aef: 213,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 16x12',
    tipo: 'Louver exterior',
    ext: '16×12"',
    w: 40.6,
    h: 30.5,
    aef: 325,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 20x12',
    tipo: 'Louver exterior',
    ext: '20×12"',
    w: 50.8,
    h: 30.5,
    aef: 418,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 24x12',
    tipo: 'Louver exterior',
    ext: '24×12"',
    w: 61,
    h: 30.5,
    aef: 510,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 30x12',
    tipo: 'Louver exterior',
    ext: '30×12"',
    w: 76.2,
    h: 30.5,
    aef: 641,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 36x12',
    tipo: 'Louver exterior',
    ext: '36×12"',
    w: 91.4,
    h: 30.5,
    aef: 780,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 12x16',
    tipo: 'Louver exterior',
    ext: '12×16"',
    w: 30.5,
    h: 40.6,
    aef: 362,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 16x16',
    tipo: 'Louver exterior',
    ext: '16×16"',
    w: 40.6,
    h: 40.6,
    aef: 501,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 20x16',
    tipo: 'Louver exterior',
    ext: '20×16"',
    w: 50.8,
    h: 40.6,
    aef: 641,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 24x16',
    tipo: 'Louver exterior',
    ext: '24×16"',
    w: 61,
    h: 40.6,
    aef: 780,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 30x16',
    tipo: 'Louver exterior',
    ext: '30×16"',
    w: 76.2,
    h: 40.6,
    aef: 984,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 36x16',
    tipo: 'Louver exterior',
    ext: '36×16"',
    w: 91.4,
    h: 40.6,
    aef: 1198,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 12x20',
    tipo: 'Louver exterior',
    ext: '12×20"',
    w: 30.5,
    h: 50.8,
    aef: 464,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 16x20',
    tipo: 'Louver exterior',
    ext: '16×20"',
    w: 40.6,
    h: 50.8,
    aef: 678,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 20x20',
    tipo: 'Louver exterior',
    ext: '20×20"',
    w: 50.8,
    h: 50.8,
    aef: 863,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 24x20',
    tipo: 'Louver exterior',
    ext: '24×20"',
    w: 61,
    h: 50.8,
    aef: 1049,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 30x20',
    tipo: 'Louver exterior',
    ext: '30×20"',
    w: 76.2,
    h: 50.8,
    aef: 1328,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 36x20',
    tipo: 'Louver exterior',
    ext: '36×20"',
    w: 91.4,
    h: 50.8,
    aef: 1616,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 12x24',
    tipo: 'Louver exterior',
    ext: '12×24"',
    w: 30.5,
    h: 61,
    aef: 603,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 16x24',
    tipo: 'Louver exterior',
    ext: '16×24"',
    w: 40.6,
    h: 61,
    aef: 845,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 20x24',
    tipo: 'Louver exterior',
    ext: '20×24"',
    w: 50.8,
    h: 61,
    aef: 1086,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 24x24',
    tipo: 'Louver exterior',
    ext: '24×24"',
    w: 61,
    h: 61,
    aef: 1328,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 30x24',
    tipo: 'Louver exterior',
    ext: '30×24"',
    w: 76.2,
    h: 61,
    aef: 1681,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-OL-4 36x24',
    tipo: 'Louver exterior',
    ext: '36×24"',
    w: 91.4,
    h: 61,
    aef: 2034,
    uso: 'ext',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 6x6',
    tipo: 'Rejilla de puerta',
    ext: '6×6"',
    w: 15.2,
    h: 15.2,
    aef: 143,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 10x6',
    tipo: 'Rejilla de puerta',
    ext: '10×6"',
    w: 25.4,
    h: 15.2,
    aef: 239,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 12x6',
    tipo: 'Rejilla de puerta',
    ext: '12×6"',
    w: 30.5,
    h: 15.2,
    aef: 287,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 10x8',
    tipo: 'Rejilla de puerta',
    ext: '10×8"',
    w: 25.4,
    h: 20.3,
    aef: 319,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 12x8',
    tipo: 'Rejilla de puerta',
    ext: '12×8"',
    w: 30.5,
    h: 20.3,
    aef: 383,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 10x10',
    tipo: 'Rejilla de puerta',
    ext: '10×10"',
    w: 25.4,
    h: 25.4,
    aef: 399,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 18x6',
    tipo: 'Rejilla de puerta',
    ext: '18×6"',
    w: 45.7,
    h: 15.2,
    aef: 431,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 14x8',
    tipo: 'Rejilla de puerta',
    ext: '14×8"',
    w: 35.6,
    h: 20.3,
    aef: 447,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 16x8',
    tipo: 'Rejilla de puerta',
    ext: '16×8"',
    w: 40.6,
    h: 20.3,
    aef: 511,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 12x12',
    tipo: 'Rejilla de puerta',
    ext: '12×12"',
    w: 30.5,
    h: 30.5,
    aef: 575,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 16x12',
    tipo: 'Rejilla de puerta',
    ext: '16×12"',
    w: 40.6,
    h: 30.5,
    aef: 767,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 20x10',
    tipo: 'Rejilla de puerta',
    ext: '20×10"',
    w: 50.8,
    h: 25.4,
    aef: 799,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 18x12',
    tipo: 'Rejilla de puerta',
    ext: '18×12"',
    w: 45.7,
    h: 30.5,
    aef: 863,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 24x12',
    tipo: 'Rejilla de puerta',
    ext: '24×12"',
    w: 61,
    h: 30.5,
    aef: 1151,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 18x18',
    tipo: 'Rejilla de puerta',
    ext: '18×18"',
    w: 45.7,
    h: 45.7,
    aef: 1295,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 30x12',
    tipo: 'Rejilla de puerta',
    ext: '30×12"',
    w: 76.2,
    h: 30.5,
    aef: 1439,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Laminaire',
    ref: 'L-DGD 24x18',
    tipo: 'Rejilla de puerta',
    ext: '24×18"',
    w: 61,
    h: 45.7,
    aef: 1727,
    uso: 'int',
    origen: 'nacional',
  },
  {
    marca: 'Koolair',
    ref: '25-H 200x100',
    tipo: 'Toma aire exterior',
    ext: '22,8×12,8',
    w: 20,
    h: 10,
    aef: 54,
    uso: 'ext',
    origen: 'importado',
  },
  {
    marca: 'Koolair',
    ref: '25-H 300x100',
    tipo: 'Toma aire exterior',
    ext: '32,8×12,8',
    w: 30,
    h: 10,
    aef: 81,
    uso: 'ext',
    origen: 'importado',
  },
  {
    marca: 'Koolair',
    ref: '25-H 400x100',
    tipo: 'Toma aire exterior',
    ext: '42,8×12,8',
    w: 40,
    h: 10,
    aef: 108,
    uso: 'ext',
    origen: 'importado',
  },
  {
    marca: 'Koolair',
    ref: '25-H 500x100',
    tipo: 'Toma aire exterior',
    ext: '52,8×12,8',
    w: 50,
    h: 10,
    aef: 135,
    uso: 'ext',
    origen: 'importado',
  },
  {
    marca: 'Koolair',
    ref: '25-H 200x150',
    tipo: 'Toma aire exterior',
    ext: '22,8×17,8',
    w: 20,
    h: 15,
    aef: 81,
    uso: 'ext',
    origen: 'importado',
  },
  {
    marca: 'Koolair',
    ref: '25-H 400x150',
    tipo: 'Toma aire exterior',
    ext: '42,8×17,8',
    w: 40,
    h: 15,
    aef: 215,
    uso: 'ext',
    origen: 'importado',
  },
  {
    marca: 'Koolair',
    ref: '25-H 300x200',
    tipo: 'Toma aire exterior',
    ext: '32,8×22,8',
    w: 30,
    h: 20,
    aef: 215,
    uso: 'ext',
    origen: 'importado',
  },
  {
    marca: 'Koolair',
    ref: '25-H 400x200',
    tipo: 'Toma aire exterior',
    ext: '42,8×22,8',
    w: 40,
    h: 20,
    aef: 269,
    uso: 'ext',
    origen: 'importado',
  },
  {
    marca: 'Koolair',
    ref: '25-H 300x250',
    tipo: 'Toma aire exterior',
    ext: '32,8×27,8',
    w: 30,
    h: 25,
    aef: 269,
    uso: 'ext',
    origen: 'importado',
  },
  {
    marca: 'Koolair',
    ref: '25-H 450x200',
    tipo: 'Toma aire exterior',
    ext: '47,8×22,8',
    w: 45,
    h: 20,
    aef: 323,
    uso: 'ext',
    origen: 'importado',
  },
  {
    marca: 'Koolair',
    ref: '25-H 300x300',
    tipo: 'Toma aire exterior',
    ext: '32,8×32,8',
    w: 30,
    h: 30,
    aef: 360,
    uso: 'ext',
    origen: 'importado',
  },
  {
    marca: 'Koolair',
    ref: '25-H 600x200',
    tipo: 'Toma aire exterior',
    ext: '62,8×22,8',
    w: 60,
    h: 20,
    aef: 480,
    uso: 'ext',
    origen: 'importado',
  },
  {
    marca: 'Koolair',
    ref: '25-H 400x300',
    tipo: 'Toma aire exterior',
    ext: '42,8×32,8',
    w: 40,
    h: 30,
    aef: 480,
    uso: 'ext',
    origen: 'importado',
  },
  {
    marca: 'TROX',
    ref: 'AGS 225x125',
    tipo: 'Paso de aire (puerta/muro)',
    ext: '25,3×15,9',
    w: 22.5,
    h: 12.5,
    aef: 80,
    uso: 'int',
    origen: 'importado',
  },
  {
    marca: 'TROX',
    ref: 'AGS 325x125',
    tipo: 'Paso de aire (puerta/muro)',
    ext: '35,3×15,9',
    w: 32.5,
    h: 12.5,
    aef: 120,
    uso: 'int',
    origen: 'importado',
  },
  {
    marca: 'TROX',
    ref: 'AGS 425x125',
    tipo: 'Paso de aire (puerta/muro)',
    ext: '45,3×15,9',
    w: 42.5,
    h: 12.5,
    aef: 160,
    uso: 'int',
    origen: 'importado',
  },
  {
    marca: 'TROX',
    ref: 'AGS 525x125',
    tipo: 'Paso de aire (puerta/muro)',
    ext: '55,3×15,9',
    w: 52.5,
    h: 12.5,
    aef: 200,
    uso: 'int',
    origen: 'importado',
  },
  {
    marca: 'TROX',
    ref: 'AGS 625x125',
    tipo: 'Paso de aire (puerta/muro)',
    ext: '65,3×15,9',
    w: 62.5,
    h: 12.5,
    aef: 240,
    uso: 'int',
    origen: 'importado',
  },
  {
    marca: 'TROX',
    ref: 'AGS 825x125',
    tipo: 'Paso de aire (puerta/muro)',
    ext: '85,3×15,9',
    w: 82.5,
    h: 12.5,
    aef: 320,
    uso: 'int',
    origen: 'importado',
  },
  {
    marca: 'TROX',
    ref: 'AGS 325x225',
    tipo: 'Paso de aire (puerta/muro)',
    ext: '35,3×25,9',
    w: 32.5,
    h: 22.5,
    aef: 270,
    uso: 'int',
    origen: 'importado',
  },
  {
    marca: 'TROX',
    ref: 'AGS 425x225',
    tipo: 'Paso de aire (puerta/muro)',
    ext: '45,3×25,9',
    w: 42.5,
    h: 22.5,
    aef: 360,
    uso: 'int',
    origen: 'importado',
  },
  {
    marca: 'TROX',
    ref: 'AGS 525x225',
    tipo: 'Paso de aire (puerta/muro)',
    ext: '55,3×25,9',
    w: 52.5,
    h: 22.5,
    aef: 450,
    uso: 'int',
    origen: 'importado',
  },
  {
    marca: 'TROX',
    ref: 'AGS 625x225',
    tipo: 'Paso de aire (puerta/muro)',
    ext: '65,3×25,9',
    w: 62.5,
    h: 22.5,
    aef: 540,
    uso: 'int',
    origen: 'importado',
  },
  {
    marca: 'TROX',
    ref: 'AGS 425x325',
    tipo: 'Paso de aire (puerta/muro)',
    ext: '45,3×35,9',
    w: 42.5,
    h: 32.5,
    aef: 560,
    uso: 'int',
    origen: 'importado',
  },
  {
    marca: 'TROX',
    ref: 'AGS 525x325',
    tipo: 'Paso de aire (puerta/muro)',
    ext: '55,3×35,9',
    w: 52.5,
    h: 32.5,
    aef: 700,
    uso: 'int',
    origen: 'importado',
  },
];
